### ISSUE TITLE
groovy error : No signature of method

### ISSUE THREAD

**Issue by pifou25** [mgwoj/Thinq-MQTT-Proxy#3]
Hello

I try the projet on Docker environment, but have this error, here is the full stacktrace:

```
21:08:00.460 [main] INFO  ThinqMqttProxy - Starting Thinq Mqtt Proxy...
21:08:01.434 [main] INFO  Mqtt - starting connection the server tcp://mqtt:1883...
21:08:02.229 [main] INFO  Mqtt - connected!
Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: org.apache.http.client.ClientProtocolException.getResponse() is applicable for argument types: () values: []
Possible solutions: getMessage()
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:88)
        at ThinQ_Integration.lgAPIPost(ThinQ_Integration.groovy:561)
        at ThinQ_Integration$lgAPIPost$0.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
        at ThinQ_Integration.register(ThinQ_Integration.groovy:635)
        at ThinQ_Integration.prefDevices(ThinQ_Integration.groovy:272)
        at ThinQ_Integration$prefDevices.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
        at ThinqMqttProxy.doRun(ThinqMqttProxy.groovy:43)
        at ThinqMqttProxy.main(ThinqMqttProxy.groovy:18)
```
Also, I'm not sure about how the user should authenticate with user / password, or any token key ? there is no such information inthe state.json example, did I miss something ?

Inside the docker container, I'm using maven 3.8 and openjdk11.
Thanks for helping !

**Comment by pifou25** [comment]
Same error ( or is it a different one ? ) What is "invalid request parameters" and how to fix it ?

```
09:40:50.940 [main] INFO ThinqMqttProxy - Starting Thinq Mqtt Proxy...
09:40:52.096 [main] INFO Mqtt - starting connection the server tcp://mqtt-server.lan:1883...
09:40:52.749 [main] INFO Mqtt - connected!
09:40:56.798 [main] ERROR ThinQ_Integration - ThinQ getAccessToken([code:, grant_type:authorization_code, redirect_uri:https://kr.m.lgaccount.com/login/iabClose]) - OAuth error: LG.OAUTH.EC.1005: Invalid request parameters.
09:40:56.814 [main] WARN ThinQ_Integration - ThinQ Unable to validate OAuth Code LG.OAUTH.EC.1005. Click next to return to the main page and try again
Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: ThinQ_Integration.dynamicPage() is applicable for argument types: (LinkedHashMap, ThinQ_Integration$_returnErrorPage_closure5) values: [[name:prefError, title:Error Occurred, nextPage:prefMain, uninstall:false, ...], ...]
  at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
  at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:80)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
  at ThinQ_Integration.returnErrorPage(ThinQ_Integration.groovy:305)
  at ThinQ_Integration$returnErrorPage$1.callCurrent(Unknown Source)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
  at ThinQ_Integration.prefDevices(ThinQ_Integration.groovy:266)
  at ThinQ_Integration$prefDevices.call(Unknown Source)
haus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at ThinqMqttProxy.doRun(ThinqMqttProxy.groovy:43)
at ThinqMqttProxy.main(ThinqMqttProxy.groovy:18)

```
